[workspace]
resolver = "2"
members = [
    "crates/petaplot-core",
    "crates/petaplot-render",
    "crates/petaplot",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Fidel Echevarria <contact@petaplot.dev>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/petaplot/petaplot"
homepage = "https://petaplot.dev"
description = "Ultra-fast, zero-copy time-series visualizer engineered for terabyte-scale datasets."
readme = "README.md"

[workspace.dependencies]
# Internas
petaplot-core = { path = "crates/petaplot-core", version = "0.1.0" }
petaplot-render = { path = "crates/petaplot-render", version = "0.1.0" }

# Rendimiento e I/O
memmap2 = "0.9"
bytemuck = { version = "1.18", features = ["derive"] }
rayon = "1.10"
arrow-array = "53.0"
parquet = "53.0"
dirs = "5.0"

# Gráficos y UI
wgpu = "23.0"
egui = "0.29"
egui-wgpu = "0.29"
eframe = "0.29"
winit = "0.30"
pollster = "0.3"

# Utilidades y Logs
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = "0.3"
crossbeam-channel = "0.5"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
